import { Hono } from "hono";
import { adminRoutes } from "./adminDevices.js";
import { authRoutes } from "./auth.js";
import { authV1Routes } from "./authV1.js";
import { cardsRoutes } from "./cards.js";
import { cardV1Routes } from "./cardV1.js";
import { chatRoutes } from "./chat.js";
import { feedRoutes } from "./feed.js";
import { healthRoutes } from "./health.js";
import { realtimeRoutes } from "./realtime.js";
import { identityRoutes } from "./identity.js";
import { vouchRoutes } from "./vouch.js";
import { campaignRoutes } from "./campaign.js";
import { activeBoardRoutes } from "./activeBoard.js";
import { walletRoutes } from "./wallet.js";
import { letteringRoutes } from "./lettering.js";
import { b2bRoutes } from "./b2b.js";
import { vluerRoutes } from "./vluer.js";
import { overlayRoutes } from "./overlay.js";
import { telecomWebhookRoutes } from "./telecomWebhook.js";
import { adminHqRoutes } from "./adminHq.js";
import { adminConsoleRoutes } from "./adminConsole.js";
import { adminMarketingRoutes } from "./adminMarketing.js";
import { homeLayoutRoutes } from "./homeLayout.js";
import { adminV1Routes } from "./adminV1.js";
import { familyProtectionRoutes } from "./familyProtection.js";
import { familyInviteRoutes } from "./familyInvite.js";
import { paymentRoutes } from "./payment.js";
import { documentsRoutes } from "./documents.js";
import { adsRoutes } from "./ads.js";
import { subscriptionCronRoutes } from "./subscriptionCron.js";
import { personalEnterpriseRoutes } from "./personalEnterprise.js";
import { shopRoutes } from "./shop.js";
import { vaultRoutes } from "./vault.js";
import { sourcingRoutes } from "./sourcing.js";
import { groupbuyRoutes } from "./groupbuy.js";
import { liveRoutes } from "./live.js";
import { assetsRoutes } from "./assets.js";
import { iotRoutes } from "./iot.js";
import { mailRoutes } from "./mail.js";
import { officeRoutes } from "./office.js";
import { aiRoutes } from "./ai.js";
import { calendarRoutes } from "./calendar.js";
import { memoRoutes } from "./memo.js";
import { vmingConsentRoutes } from "./vmingConsent.js";
import { vmingRoutes } from "./vming.js";
import { fraudRoutes } from "./fraud.js";
import { calendarNoticeRoutes } from "./calendarNotice.js";
import { pricingConfigRoutes } from "./pricingConfig.js";
import { broadcastLineRoutes } from "./broadcastLine.js";
import { familyCrossSecurityRoutes } from "./familyCrossSecurity.js";
import { translateRoutes } from "./translate.js";
import { spellV1Routes } from "./spellV1.js";
import { searchV1Routes } from "./searchV1.js";
import { auctionRoutes } from "./auction.js";
import { scrapeProductRoutes } from "./scrapeProduct.js";
import { mediaRoutes } from "./media.js";
import { sellerVodRoutes } from "./sellerVod.js";

/** `/api` 아래에 마운트되는 라우트 묶음 */
export const apiRoutes = new Hono();

apiRoutes.route("/", healthRoutes);
apiRoutes.route("/auth", authRoutes);
apiRoutes.route("/v1/auth", authV1Routes);
apiRoutes.route("/identity", identityRoutes);
apiRoutes.route("/chat", chatRoutes);
apiRoutes.route("/vouch", vouchRoutes);
apiRoutes.route("/admin/hq", adminHqRoutes);
apiRoutes.route("/admin/console", adminConsoleRoutes);
apiRoutes.route("/admin", adminMarketingRoutes);
apiRoutes.route("/admin", adminRoutes);
apiRoutes.route("/home", homeLayoutRoutes);
apiRoutes.route("/v1/admin", adminV1Routes);
apiRoutes.route("/cards", cardsRoutes);
apiRoutes.route("/v1/card", cardV1Routes);
apiRoutes.route("/feed", feedRoutes);
apiRoutes.route("/realtime", realtimeRoutes);
apiRoutes.route("/campaign", campaignRoutes);
apiRoutes.route("/active-board", activeBoardRoutes);
apiRoutes.route("/wallet", walletRoutes);
apiRoutes.route("/lettering", letteringRoutes);
apiRoutes.route("/b2b", b2bRoutes);
apiRoutes.route("/vluer", vluerRoutes);
apiRoutes.route("/v1/overlay", overlayRoutes);
apiRoutes.route("/webhooks/telecom", telecomWebhookRoutes);
apiRoutes.route("/family-protection", familyProtectionRoutes);
apiRoutes.route("/family", familyInviteRoutes);
apiRoutes.route("/payment", paymentRoutes);
apiRoutes.route("/documents", documentsRoutes);
apiRoutes.route("/ads", adsRoutes);
apiRoutes.route("/cron", subscriptionCronRoutes);
apiRoutes.route("/", personalEnterpriseRoutes);
apiRoutes.route("/shop", shopRoutes);
apiRoutes.route("/vault", vaultRoutes);
apiRoutes.route("/sourcing", sourcingRoutes);
apiRoutes.route("/groupbuy", groupbuyRoutes);
apiRoutes.route("/live", liveRoutes);
apiRoutes.route("/assets", assetsRoutes);
apiRoutes.route("/iot", iotRoutes);
apiRoutes.route("/mail", mailRoutes);
apiRoutes.route("/office", officeRoutes);
apiRoutes.route("/ai", aiRoutes);
apiRoutes.route("/calendar", calendarRoutes);
apiRoutes.route("/calendar/notice", calendarNoticeRoutes);
apiRoutes.route("/memo", memoRoutes);
apiRoutes.route("/vming/consent", vmingConsentRoutes);
apiRoutes.route("/vming", vmingRoutes);
apiRoutes.route("/fraud", fraudRoutes);
apiRoutes.route("/pricing", pricingConfigRoutes);
apiRoutes.route("/broadcast-line", broadcastLineRoutes);
apiRoutes.route("/family-cross-security", familyCrossSecurityRoutes);
apiRoutes.route("/translate", translateRoutes);
apiRoutes.route("/v1/spell", spellV1Routes);
apiRoutes.route("/v1/search", searchV1Routes);
apiRoutes.route("/auction", auctionRoutes);
apiRoutes.route("/scrape-product", scrapeProductRoutes);
apiRoutes.route("/media", mediaRoutes);
apiRoutes.route("/media-commerce", sellerVodRoutes);
